package com.scripttube.android.ScriptTube.Utilities.HelperClasses;

public class HelperClass {
    public static String getTermsOfServiceHeading() {
        return "Terms of Service";
    }

    public static String getPrivacyPolicyHeading() {
        return "Privacy Policy";
    }

    public static String getCopyrightPolicyHeading() {
        return "Copyright Policy";
    }

    public static String getTermsOfServiceDescription() {
        return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut varius justo. Nullam et urna in ante posuere suscipit. Vestibulum ut efficitur tellus. Aliquam consectetur laoreet ipsum. Proin a orci ullamcorper, fringilla enim in, auctor velit. Sed tristique condimentum massa, vel vestibulum sem scelerisque non. Morbi iaculis vel leo et venenatis. Proin tempor orci vitae dui mollis, a cursus neque facilisis. Mauris massa orci, pharetra et tincidunt nec, lacinia non leo. Praesent ex orci, porttitor eu tempor a, accumsan vel est. Nunc facilisis facilisis imperdiet. Cras auctor nisl id diam dapibus, ut euismod enim ullamcorper. Donec condimentum mi nec justo sagittis, condimentum mattis nisl pulvinar. Maecenas leo nulla, ullamcorper non nulla sit amet, pulvinar convallis augue. Etiam consequat, turpis at sodales faucibus, quam risus ornare nulla, id facilisis dolor velit sit amet dolor.\n" +
                "\n" +
                "Nulla arcu nisl, gravida ut cursus ut, vestibulum et nulla. Mauris dignissim nunc sapien, sit amet placerat tellus egestas vel. In euismod purus et magna pharetra, non elementum risus aliquam. Donec tristique non felis sed suscipit. Donec a tincidunt quam. Phasellus augue dolor, aliquet condimentum placerat ut, ornare condimentum enim. Etiam a efficitur dolor. Sed ac hendrerit libero.\n" +
                "\n" +
                "Cras porttitor erat sed enim convallis, sed auctor turpis molestie. Pellentesque volutpat lectus id pretium suscipit. Aenean et fringilla lacus. Integer consectetur tristique est sit amet dignissim. Curabitur pulvinar tortor sed purus pharetra, at pharetra lorem tincidunt. Ut vel quam et massa tempus consectetur. Sed fringilla leo et justo interdum, eget rhoncus eros congue. Vivamus imperdiet ante arcu, vehicula porttitor dui maximus non. Mauris velit enim, dapibus et vestibulum ac, cursus eget turpis. Pellentesque et neque justo. Suspendisse potenti. Nam bibendum hendrerit est, euismod finibus tellus rutrum in. Vivamus et luctus libero, sit amet mollis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer neque nunc, mollis feugiat augue in, scelerisque bibendum ligula. Integer sodales fringilla arcu ut hendrerit.\n" +
                "\n" +
                "Pellentesque hendrerit tempor velit, at consectetur dui mollis at. Ut tortor nulla, molestie vel pretium eget, sollicitudin non purus. Nam rhoncus ullamcorper elementum. Praesent sollicitudin tristique diam ut mattis. Nullam tempus ex libero, in porta metus convallis nec. Quisque et ipsum eget turpis finibus aliquet. Maecenas nisi libero, tempor vel porta ut, luctus pulvinar erat. Vestibulum sit amet molestie ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam imperdiet et orci non laoreet. Pellentesque mollis lorem ac velit rhoncus mattis. Nunc tempus hendrerit velit ac laoreet.\n" +
                "\n" +
                "Donec ut luctus dui, commodo vestibulum risus. Nunc blandit mattis magna, non feugiat lorem posuere id. Etiam scelerisque, quam cursus sagittis feugiat, metus nunc ornare dolor, ut congue augue eros vel nunc. Vestibulum ac venenatis nulla, non molestie quam. Quisque in interdum tellus. Duis eget sollicitudin metus. Vestibulum efficitur pellentesque augue, vitae tincidunt massa tempor viverra. Duis eleifend risus et urna ultrices, vel interdum dui aliquam.\n" +
                "\n" +
                "Vestibulum mollis, nulla et consectetur iaculis, elit orci efficitur turpis, ut mollis diam lacus eget risus. Nullam elit orci, finibus vitae malesuada ut, finibus ut nibh. Sed cursus magna id turpis laoreet viverra. Vivamus dolor augue, egestas eget laoreet elementum, elementum a mauris. Maecenas dignissim nisl lorem, vitae dignissim lacus tristique in. Ut convallis varius orci, sit amet molestie velit commodo non. Fusce vitae elementum odio, id semper orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam, metus et ornare sagittis, arcu sapien posuere arcu, sed gravida felis mi eget ligula. Duis ut urna mattis nulla interdum aliquet eget ac diam. Maecenas sit amet tempus diam, vel blandit augue. Nulla nec massa quis ex tristique interdum.";
    }

    public static String getPrivacyPolicyDescription() {
        return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut varius justo. Nullam et urna in ante posuere suscipit. Vestibulum ut efficitur tellus. Aliquam consectetur laoreet ipsum. Proin a orci ullamcorper, fringilla enim in, auctor velit. Sed tristique condimentum massa, vel vestibulum sem scelerisque non. Morbi iaculis vel leo et venenatis. Proin tempor orci vitae dui mollis, a cursus neque facilisis. Mauris massa orci, pharetra et tincidunt nec, lacinia non leo. Praesent ex orci, porttitor eu tempor a, accumsan vel est. Nunc facilisis facilisis imperdiet. Cras auctor nisl id diam dapibus, ut euismod enim ullamcorper. Donec condimentum mi nec justo sagittis, condimentum mattis nisl pulvinar. Maecenas leo nulla, ullamcorper non nulla sit amet, pulvinar convallis augue. Etiam consequat, turpis at sodales faucibus, quam risus ornare nulla, id facilisis dolor velit sit amet dolor.\n" +
                "\n" +
                "Nulla arcu nisl, gravida ut cursus ut, vestibulum et nulla. Mauris dignissim nunc sapien, sit amet placerat tellus egestas vel. In euismod purus et magna pharetra, non elementum risus aliquam. Donec tristique non felis sed suscipit. Donec a tincidunt quam. Phasellus augue dolor, aliquet condimentum placerat ut, ornare condimentum enim. Etiam a efficitur dolor. Sed ac hendrerit libero.\n" +
                "\n" +
                "Cras porttitor erat sed enim convallis, sed auctor turpis molestie. Pellentesque volutpat lectus id pretium suscipit. Aenean et fringilla lacus. Integer consectetur tristique est sit amet dignissim. Curabitur pulvinar tortor sed purus pharetra, at pharetra lorem tincidunt. Ut vel quam et massa tempus consectetur. Sed fringilla leo et justo interdum, eget rhoncus eros congue. Vivamus imperdiet ante arcu, vehicula porttitor dui maximus non. Mauris velit enim, dapibus et vestibulum ac, cursus eget turpis. Pellentesque et neque justo. Suspendisse potenti. Nam bibendum hendrerit est, euismod finibus tellus rutrum in. Vivamus et luctus libero, sit amet mollis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer neque nunc, mollis feugiat augue in, scelerisque bibendum ligula. Integer sodales fringilla arcu ut hendrerit.\n" +
                "\n" +
                "Pellentesque hendrerit tempor velit, at consectetur dui mollis at. Ut tortor nulla, molestie vel pretium eget, sollicitudin non purus. Nam rhoncus ullamcorper elementum. Praesent sollicitudin tristique diam ut mattis. Nullam tempus ex libero, in porta metus convallis nec. Quisque et ipsum eget turpis finibus aliquet. Maecenas nisi libero, tempor vel porta ut, luctus pulvinar erat. Vestibulum sit amet molestie ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam imperdiet et orci non laoreet. Pellentesque mollis lorem ac velit rhoncus mattis. Nunc tempus hendrerit velit ac laoreet.\n" +
                "\n" +
                "Donec ut luctus dui, commodo vestibulum risus. Nunc blandit mattis magna, non feugiat lorem posuere id. Etiam scelerisque, quam cursus sagittis feugiat, metus nunc ornare dolor, ut congue augue eros vel nunc. Vestibulum ac venenatis nulla, non molestie quam. Quisque in interdum tellus. Duis eget sollicitudin metus. Vestibulum efficitur pellentesque augue, vitae tincidunt massa tempor viverra. Duis eleifend risus et urna ultrices, vel interdum dui aliquam.\n" +
                "\n" +
                "Vestibulum mollis, nulla et consectetur iaculis, elit orci efficitur turpis, ut mollis diam lacus eget risus. Nullam elit orci, finibus vitae malesuada ut, finibus ut nibh. Sed cursus magna id turpis laoreet viverra. Vivamus dolor augue, egestas eget laoreet elementum, elementum a mauris. Maecenas dignissim nisl lorem, vitae dignissim lacus tristique in. Ut convallis varius orci, sit amet molestie velit commodo non. Fusce vitae elementum odio, id semper orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam, metus et ornare sagittis, arcu sapien posuere arcu, sed gravida felis mi eget ligula. Duis ut urna mattis nulla interdum aliquet eget ac diam. Maecenas sit amet tempus diam, vel blandit augue. Nulla nec massa quis ex tristique interdum.";
    }

    public static String getCopyrightPolicyDescription() {
        return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut varius justo. Nullam et urna in ante posuere suscipit. Vestibulum ut efficitur tellus. Aliquam consectetur laoreet ipsum. Proin a orci ullamcorper, fringilla enim in, auctor velit. Sed tristique condimentum massa, vel vestibulum sem scelerisque non. Morbi iaculis vel leo et venenatis. Proin tempor orci vitae dui mollis, a cursus neque facilisis. Mauris massa orci, pharetra et tincidunt nec, lacinia non leo. Praesent ex orci, porttitor eu tempor a, accumsan vel est. Nunc facilisis facilisis imperdiet. Cras auctor nisl id diam dapibus, ut euismod enim ullamcorper. Donec condimentum mi nec justo sagittis, condimentum mattis nisl pulvinar. Maecenas leo nulla, ullamcorper non nulla sit amet, pulvinar convallis augue. Etiam consequat, turpis at sodales faucibus, quam risus ornare nulla, id facilisis dolor velit sit amet dolor.\n" +
                "\n" +
                "Nulla arcu nisl, gravida ut cursus ut, vestibulum et nulla. Mauris dignissim nunc sapien, sit amet placerat tellus egestas vel. In euismod purus et magna pharetra, non elementum risus aliquam. Donec tristique non felis sed suscipit. Donec a tincidunt quam. Phasellus augue dolor, aliquet condimentum placerat ut, ornare condimentum enim. Etiam a efficitur dolor. Sed ac hendrerit libero.\n" +
                "\n" +
                "Cras porttitor erat sed enim convallis, sed auctor turpis molestie. Pellentesque volutpat lectus id pretium suscipit. Aenean et fringilla lacus. Integer consectetur tristique est sit amet dignissim. Curabitur pulvinar tortor sed purus pharetra, at pharetra lorem tincidunt. Ut vel quam et massa tempus consectetur. Sed fringilla leo et justo interdum, eget rhoncus eros congue. Vivamus imperdiet ante arcu, vehicula porttitor dui maximus non. Mauris velit enim, dapibus et vestibulum ac, cursus eget turpis. Pellentesque et neque justo. Suspendisse potenti. Nam bibendum hendrerit est, euismod finibus tellus rutrum in. Vivamus et luctus libero, sit amet mollis lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer neque nunc, mollis feugiat augue in, scelerisque bibendum ligula. Integer sodales fringilla arcu ut hendrerit.\n" +
                "\n" +
                "Pellentesque hendrerit tempor velit, at consectetur dui mollis at. Ut tortor nulla, molestie vel pretium eget, sollicitudin non purus. Nam rhoncus ullamcorper elementum. Praesent sollicitudin tristique diam ut mattis. Nullam tempus ex libero, in porta metus convallis nec. Quisque et ipsum eget turpis finibus aliquet. Maecenas nisi libero, tempor vel porta ut, luctus pulvinar erat. Vestibulum sit amet molestie ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam imperdiet et orci non laoreet. Pellentesque mollis lorem ac velit rhoncus mattis. Nunc tempus hendrerit velit ac laoreet.\n" +
                "\n" +
                "Donec ut luctus dui, commodo vestibulum risus. Nunc blandit mattis magna, non feugiat lorem posuere id. Etiam scelerisque, quam cursus sagittis feugiat, metus nunc ornare dolor, ut congue augue eros vel nunc. Vestibulum ac venenatis nulla, non molestie quam. Quisque in interdum tellus. Duis eget sollicitudin metus. Vestibulum efficitur pellentesque augue, vitae tincidunt massa tempor viverra. Duis eleifend risus et urna ultrices, vel interdum dui aliquam.\n" +
                "\n" +
                "Vestibulum mollis, nulla et consectetur iaculis, elit orci efficitur turpis, ut mollis diam lacus eget risus. Nullam elit orci, finibus vitae malesuada ut, finibus ut nibh. Sed cursus magna id turpis laoreet viverra. Vivamus dolor augue, egestas eget laoreet elementum, elementum a mauris. Maecenas dignissim nisl lorem, vitae dignissim lacus tristique in. Ut convallis varius orci, sit amet molestie velit commodo non. Fusce vitae elementum odio, id semper orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam, metus et ornare sagittis, arcu sapien posuere arcu, sed gravida felis mi eget ligula. Duis ut urna mattis nulla interdum aliquet eget ac diam. Maecenas sit amet tempus diam, vel blandit augue. Nulla nec massa quis ex tristique interdum.";
    }
}
