//
//  URLHelper.swift

import Foundation

class URLHelper{
    static let BASE_URL: String               =  "https://raaise.app/backend/" //"https://raaise.app/backend/"
    //"http://82.180.161.7/backend/"
    //"http://13.233.101.218:3000/"
      //"https://raaise.app/"
    static let SEGMENTCLIENT: String          =       ""
    static let SEGMENTAPIVERSION: String      =       ""
    static let SOCKET_URL: String               = "http://34.230.148.158:5000"
    //"http://13.233.101.218:5000"//"http://82.180.161.7:5000"
    static let LOGIN_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/login"
    static let UPDATE_PRIVACY_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/update-invite-privacy-control"
    static let SIGNIN_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/register"
    static let GET_PROFILE_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-profile"
    static let CHANGE_PASSWORD = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/change-password"
    static let GET_UPDATE_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/update-profile"
    static let FB_LOGIN_URLx = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/facebook-login"
    static let FORGOT_PASSWORD = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/forget-password"
    static let VERIFY_OTP = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/otp-verify"
    static let RESET_PASSWORD = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/reset-password"
    static let GET_SETTINGS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/general-settings"
    static let DEACTIVATE_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/deactive-account"
    static let GET_AUDIO_LIST_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/audio-list"
    static let DELETE_ACCOUNT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/delete-user"
    static let LOGOUT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/user-logout"
    static let NOTIFICATIONS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/notification-on-off"
    static let UPLOAD_VIDEO_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/upload-video"
    static let GET_USER_PROFILE_VIDEOS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-video"
    static let GET_GLOBAL_VIDEOS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-global-video"
    static let VIDEO_LIKE_UNLIKE_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/video-like-dislike"
    static let VIDEO_REPORT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/report-video"
    static let GOOGLE_LOGIN_URLx = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/google-login"
    static let GET_VIDEO_COMMENTS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-videos-comment"
    static let USER_FOLLOW_UNFOLLOW_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/user-follow-unfollow"
    static let POST_COMMENTS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/video-comment"
    static let EDIT_COMMENTS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/edit-video-comment"
    static let EDIT_REPLY_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/edit-comment-reply"
    static let DELETE_COMMENTS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/video-comment-delete"
    static let DELETE_REPLY_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/delete-comment-reply"
    static let POST_REPLY_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/comment-reply"
    static let GET_USER_FOLLOWER_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/user-followers"
    static let GET_USER_FOLLOWING_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/user-following"
    static let GET_USER_PROFILE_BY_ID_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-profile-by-id"
    static let GET_USER_VIDEOS_BY_ID_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-videos-by-id"
    static let GET_VIDEOS_BY_AUDIO_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-videos-by-audio-id"
    static let ADD_BANK_DETAILS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/add-update-bank-details"
    static let GET_CARDS_LIST_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-cards"
    static let GET_VIDEO_CHAT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/live-room/get-live-room-chat"
    static let DELETE_POST_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/delete-video"
    static let EDIT_POST_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/edit-video-caption"
    static let GET_VIDEO_CATEGORY_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-categories"
    static let VIDEO_COUNT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/video-view-by-user"
    static let GET_OTHER_USER_FOLLOWING_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-follwing-list"
    static let GET_OTHER_USER_FOLLOWER_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-follwers-list"
    static let GLOBAL_SEARCH_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/global-search"
    static let GET_USER_LIST_FOR_ROOM = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/live-room/search-users-by-privacy-control"
    static let ADD_CARD_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/add-card"
    static let PAYMENT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/make-payment-by-card-id"
    static let DELETE_CARD_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/delete-cards"
    static let GET_NOTIFICATIONS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-notifications"
    static let SET_DEFAULT_CARD_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/select-default-card"
    static let GET_CHAT_LIST_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-chat-list"
    static let GET_CHAT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-single-chat"
    static let GET_SINGLE_VIDEO_DETAIL_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-video"
    static let READ_NOTIFICATIONS_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/read-single-notification"
    static let GET_UNREAD_CHAT_COUNT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-message-count"
    static let SHARE_VIDEO_TO_CHAT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/share-video"
    static let GET_UNREAD_NOTIFICATION_COUNT_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-notification-unreadcount"
    static let CREATE_CHAT_SLUG_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/profile-chat"
    static let APPLE_LOGIN_URLx = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/apple-login"
    static let DONATION_RAISEDx = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/donation-history"
    static let VIDEO_ANALYTICSx = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-video-donation-history"
    static let CLAIM_DONATIONx = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/send-request-to-payment"
    static let WITHDRAW_LIST = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-user-withdrawal-request"
    static let BLOCK_USER = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/block-user"
    static let GET_LIVE_ROOM = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-live-rooms"
    static let GET_LIVE_ROOM_PUBLIC = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-public-live-rooms"
    static let GET_LIVE_ROOM_BY_SLUG = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/get-live-room-by-slug"
    static let JOIN_LIVE_ROOM = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/join-public-live-room"
    static let LEAVE_LIVE_ROOM = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/leave-live-room"
    static let UPDATE_LIVE_ROOM = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/update-live-room"
    static let CREATE_LIVE_ROOM = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/create-live-room"
    static let SEND_MESSAGE_URL = BASE_URL+SEGMENTCLIENT+SEGMENTAPIVERSION+"user/live-room/chat-send-message"
}

